[general]
import = ["/home/anupam/.config/alacritty/colors/tokyo-night.toml"]
working_directory = "/home/anupam"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold"

[font.italic]
style = "Regular"

[font.normal]
family = "FiraCode"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[scrolling]
history = 10000

# [terminal.shell]
# program = "/usr/bin/zsh"
[terminal]
# shell = "/home/anupam/.nix-profile/bin/fish"

[window]
opacity = 1
[window.dimensions]
columns = 80
lines = 24
