vim.g.dart_format_on_save = 1
vim.g.tex_flavor = 'latex'
vim.g.netrw_banner = 0
vim.g.netrw_browse_split = 0
vim.g.netrw_winsize = 20
vim.g.netrw_keepdir = 0
vim.g['bujo#window_width'] = 100
vim.g.neovide_transparency= 0.92
vim.g.neovide_floating_blur_amount_x = 2.0
vim.g.neovide_floating_blur_amount_y = 2.0
